name: frontend
description: "BCGx Challenge - Team 1 Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  get_it: ^8.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  vitality: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_native_splash:
  android: false
  ios: false
  web: true
  color: "#F9F9F9"
  image: assets/logo_big.png
